title: Kodama's Portfolio
markdown: kramdown

# for atom feed
author:
  name: Kodama Hideaki
  email: cshd23008@g.nihon-u.ac.jp

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

url: "https://kodama3008.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: kodama300
